replicaCount: 1
restartPolicy: Always

container:
  image: hypnosapos/visdom:latest
  pullPolicy: IfNotPresent
  envs:
    logging_level: DEBUG
    env_path: /usr/share/visdom
    port: 8097

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port: 8097
  nodePort: ""

podAnnotations: {}

resources: {}

nodeSelector: {}

persistence:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: standard

