apiVersion: machinelearning.seldon.io/v1alpha1
kind: SeldonDeployment
metadata:
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{ .Release.Service }}
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{ .Release.Name }}
    # This makes it easy to audit chart usage.
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  annotations:
    project_name: {{ .Values.project }}
    deployment_version: v1
  name: {{ .Values.name }}
  oauth_key: {{ .Values.seldon.oauth_key }}
  oauth_secret: {{ .Values.seldon.auth_secret }}
  predictors:
  - componentSpec:
      spec:
        containers:
        - image: "{{ .Values.container.image.name }}:{{ .Values.container.image.tag }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          name: {{ .Values.name }}
          resources:
            requests:
              memory: "2Mi"
        terminationGracePeriodSeconds: 20
    graph:
      children: []
      name: {{ .Values.name }}
      endpoint:
        type: "REST"
      type: "MODEL"
    name: {{ .Values.name }}
    replicas: 1
    annotations:
    predictor_version: v1
